/**
 * 通用样式：颜色一律走 --dsh-mem-* 令牌（随 Light/Dark 主题自动切换）；
 * 视觉与交互态（hover/active/focus）在注入样式表的类里（theme.ts），这里只留布局。
 */
import type { CSSProperties } from 'react';

export const S: Record<string, CSSProperties> = {
  section: { padding: '0 4px' },
  heading: { fontSize: 16, fontWeight: 600, margin: '0 0 2px', color: 'var(--dsh-mem-text-1)' },
  intro: { fontSize: 13, color: 'var(--dsh-mem-text-3)', margin: '0 0 8px' },
  tabbar: { display: 'flex', gap: 2, borderBottom: '1px solid var(--dsh-mem-border)', marginBottom: 14 },
  error: {
    marginTop: 10,
    fontSize: 13,
    color: 'var(--dsh-mem-danger)',
    whiteSpace: 'pre-wrap',
  },
  hint: { marginTop: 12, fontSize: 12, color: 'var(--dsh-mem-text-3)' },
  toolbar: { display: 'flex', gap: 6, marginBottom: 8, flexWrap: 'wrap', alignItems: 'center' },
  card: {
    padding: 0,
    marginBottom: 0,
    fontSize: 13,
  },
  cardHead: { display: 'flex', alignItems: 'center', gap: 8, marginBottom: 4 },
  muted: { color: 'var(--dsh-mem-text-3)', fontSize: 12 },
  content: { lineHeight: 1.5, wordBreak: 'break-word', color: 'var(--dsh-mem-text-1)' },
  detail: {
    marginTop: 8,
    paddingTop: 8,
    borderTop: '1px dashed var(--dsh-mem-border)',
    fontSize: 12,
    fontFamily: 'ui-monospace, SFMono-Regular, Consolas, monospace',
    color: 'var(--dsh-mem-text-2)',
    whiteSpace: 'pre-wrap',
  },
  pre: {
    margin: 0,
    padding: '10px 12px',
    background: 'var(--dsh-mem-bg-inset)',
    border: '1px solid var(--dsh-mem-border)',
    borderRadius: 10,
    fontSize: 12,
    fontFamily: 'ui-monospace, SFMono-Regular, Consolas, monospace',
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
    lineHeight: 1.6,
    maxHeight: 480,
    overflow: 'auto',
  },
  switchRow: { display: 'flex', alignItems: 'center', gap: 10, padding: '6px 0' },
  switchLabel: { fontSize: 13, fontWeight: 600, minWidth: 56, color: 'var(--dsh-mem-text-1)' },
  switchDesc: { fontSize: 12, color: 'var(--dsh-mem-text-3)', lineHeight: '16px' },
  switch: {
    width: 36,
    height: 20,
    borderRadius: 999,
    position: 'relative',
    cursor: 'pointer',
    transition: 'background .15s',
    flexShrink: 0,
  },
  switchOn: { background: 'var(--dsh-mem-accent-fill)' },
  switchOff: { background: 'var(--dsh-mem-border-strong)' },
  switchDisabled: { opacity: 0.4, cursor: 'not-allowed' },
  knob: {
    position: 'absolute',
    top: 2,
    width: 16,
    height: 16,
    borderRadius: '50%',
    background: 'var(--dsh-mem-thumb)',
    transition: 'left .15s',
    boxShadow: '0 1px 2px rgba(0,0,0,.25)',
  },
  switchPanel: {
    border: 'none',
    borderRadius: 0,
    background: 'transparent',
    boxShadow: 'none',
    padding: 0,
    marginBottom: 0,
  },
  panelLabel: {
    fontSize: 12,
    fontWeight: 600,
    color: 'var(--dsh-mem-text-3)',
    margin: '12px 0 2px',
  },
  statGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(140px, 1fr))',
    gap: 8,
    marginBottom: 14,
  },
  statTile: { padding: '10px 12px' },
  statNum: { fontSize: 20, fontWeight: 650, lineHeight: '28px', color: 'var(--dsh-mem-text-1)' },
  statLabel: { fontSize: 12, color: 'var(--dsh-mem-text-3)', marginTop: 2 },
  infoRow: {
    display: 'flex',
    alignItems: 'baseline',
    gap: 12,
    padding: '5px 0',
    borderBottom: '1px solid var(--dsh-mem-border)',
  },
  infoKey: { fontSize: 12.5, color: 'var(--dsh-mem-text-3)', whiteSpace: 'nowrap', minWidth: 96 },
  infoVal: {
    fontSize: 12.5,
    color: 'var(--dsh-mem-text-1)',
    fontFamily: 'ui-monospace, SFMono-Regular, Consolas, monospace',
    wordBreak: 'break-all',
    textAlign: 'right',
    flex: 1,
  },
  seg: {
    display: 'inline-flex',
    border: '1px solid var(--dsh-mem-border)',
    borderRadius: 8,
    overflow: 'hidden',
    flexShrink: 0,
    background: 'var(--dsh-mem-bg-inset)',
  },
  segBtn: {
    padding: '4px 12px',
    fontSize: 12,
    lineHeight: '16px',
    cursor: 'pointer',
    background: 'transparent',
    color: 'var(--dsh-mem-text-2)',
    border: 'none',
    borderRight: '1px solid var(--dsh-mem-border)',
  },
  segBtnOn: {
    background: 'var(--dsh-mem-accent-fill)',
    color: '#fff',
    fontWeight: 600,
  },
  flexRow: { display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap' },
  grow: { flex: 1 },
  sceneHead: { display: 'flex', alignItems: 'baseline', gap: 10, marginBottom: 6, flexWrap: 'wrap' },
  sceneTitle: { fontSize: 13, fontWeight: 600, fontFamily: 'ui-monospace, Consolas, monospace', color: 'var(--dsh-mem-text-1)' },
};
